authors:
  shubhamdang:
    name: Shubham Dang
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/15174448
    url: https://github.com/shubhamdang
  dshaw:
    name: Dan Shaw
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/58476476
    url: https://github.com/dshaw29